### ISSUE TITLE
fix your documentation

### ISSUE THREAD

**Issue by phantamanta44** [hlaaftana/DiscordCraft#15]
![meme](http://i.imgur.com/E0JWC3y.gif)
wtf is the deal man, your ore grinder thingy is too cheap but when I made it require bedrock, now I can't even make it! What are you smoking, making it so that I can't change the recipe the way I want?
Your mod is the most overpowered I have ever seen, you should be ashamed of your incompetence. All I needed was a few thousand cobblestone and suddenly I'm at the endgame, where's the challenge?!
![meme](http://i.imgur.com/E0JWC3y.gif)
wtf is the deal man, your ore grinder thingy is too cheap but when I made it require bedrock, now I can't even make it! What are you smoking, making it so that I can't change the recipe the way I want?
Your mod is the most overpowered I have ever seen, you should be ashamed of your incompetence. All I needed was a few thousand cobblestone and suddenly I'm at the endgame, where's the challenge?!
![meme](http://i.imgur.com/E0JWC3y.gif)
wtf is the deal man, your ore grinder thingy is too cheap but when I made it require bedrock, now I can't even make it! What are you smoking, making it so that I can't change the recipe the way I want?
Your mod is the most overpowered I have ever seen, you should be ashamed of your incompetence. All I needed was a few thousand cobblestone and suddenly I'm at the endgame, where's the challenge?!
![meme](http://i.imgur.com/E0JWC3y.gif)
wtf is the deal man, your ore grinder thingy is too cheap but when I made it require bedrock, now I can't even make it! What are you smoking, making it so that I can't change the recipe the way I want?
Your mod is the most overpowered I have ever seen, you should be ashamed of your incompetence. All I needed was a few thousand cobblestone and suddenly I'm at the endgame, where's the challenge?!

**Comment by hlaaftana** [comment]
i will fix you
